spring:
  datasource:
    username: zwxbest
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://nizouba_mysql:3307/xunwu
  http:
    multipart:
      location: ~/es-test/file/
  redis:
    database: 0
    host: nizouba_redis
    port: 6379
    pool:
      min-idle: 1
    timeout: 3000
    password: redis
  session:
    store-type: redis

